### ISSUE TITLE
Feedback for “Botpress API Documentation”

### ISSUE THREAD

**Issue by ankitOpash** [botpress/documentation#134]
very bad please clearly describe the doc 

how to get bot response "outcoming" 

plz answer me as soon as

**Comment by devguilhermy** [comment]
Hello @ts-ayOpash what specific page of the API documentation are you talking about?

**Comment by franklevasseur** [comment]
Hi,

The best place to ask question and report issues about Botpress Cloud is the official Botpress [discord server](https://discord.gg/botpress).

I'll close the issue, please feel free to write us on Discord for any future problems.

Cheers,

Frank
