### ISSUE TITLE
"Set Workspace Payment Method" API endpoint not working

### ISSUE THREAD

**Issue by thetonyalvarez** [botpress/documentation#189]
I cannot get this endpoint to return anything other than a 500 error -

I call the following endpoint using PUT method:
`https://](https://api.botpress.cloud/v1/admin/workspaces/{id}/billing/payment-method`

I include my PAT token in the Authorization as a bearer token.

I send a PaymentMethod id prefixed with "pm_" as per Stripe documentation, in the body of the request:
```
{
"stripePaymentMethodId": "pm_1231231231231"
}
```

I still get a 500 error no matter if i try resetting PAT, trying different Stripe payment methods (test and live ones).

**Comment by franklevasseur** [comment]
Hi @thetonyalvarez,

Do you have an error ID that comes with your 500 ? This could help us identify where it breaks

**Comment by franklevasseur** [comment]
Hi,

The best place to ask question and report issues about Botpress Cloud is the official Botpress [discord server](https://discord.gg/botpress).

I'll close the issue, please feel free to write us on Discord for any future problems.

Cheers,

Frank
