### ISSUE TITLE
Feedback for “Building a Custom Integration”

### ISSUE THREAD

**Issue by pyxiscloud** [botpress/documentation#209]
Example from documentation not works
After "pnpm run deploy" there is not any new integrations.
Please confirm right example? Or fix exist
Thank you

**Comment by franklevasseur** [comment]
hey @pyxiscloud 

can you explain what you were trying to achieve ?

can you show me your terminal commands and logs output ?

Frank

**Comment by pyxiscloud** [comment]
Hello,
I try to make bot that will work with custom integration.
To make it, I 've started with manual on https://botpress.com/docs/developers/howTo/build-integration/
WIll try " pnpm bp deploy"
Thank you

**Comment by franklevasseur** [comment]
You'll find it by clicking on the gear, then Integrations.

These are your private integrations.

![image](https://github.com/botpress/documentation/assets/25970722/57bb079d-ab9a-4210-9448-4fadab4f9548)

Let me know if I can close the issue.

Frank
