### ISSUE TITLE
Feedback for “Hooks”

### ISSUE THREAD

**Issue by unicsoftware** [botpress/documentation#222]
How i can to use this feature.  

I would like to use in the scene of the sales confirmation or the abandoned cart in the my webstore.

Please, we need of mor examples in the youtube channel botpress

**Comment by franklevasseur** [comment]
Hi,

The best place to ask question and report issues about Botpress Cloud is the official Botpress [discord server](https://discord.gg/botpress).

I'll close the issue, please feel free to write us on Discord for any future problems.

Cheers,

Frank
