### ISSUE TITLE
Feedback for “Agents”

### ISSUE THREAD

**Issue by agpldev** [botpress/documentation#223]
Hello Botpress team,

The page https://botpress.com/docs/cloud/studio/agents/ has a section on the "Personality Agent" feature that currently references a video snippet about the "always transition" feature instead. Please correct this.

![image](https://github.com/botpress/documentation/assets/64598903/a8699970-3480-4036-aa3e-098f5bdea4c4)

Kind regards.

**Comment by franklevasseur** [comment]
Hi,

The best place to ask question and report issues about Botpress Cloud is the official Botpress [discord server](https://discord.gg/botpress).

I'll close the issue, please feel free to write us on Discord for any future problems.

Cheers,

Frank
