### ISSUE TITLE
Feedback for “Zapier” documentation

### ISSUE THREAD

**Issue by archmod** [botpress/documentation#225]
I am attempting to perform the function described in the Zapier integration page (https://botpress.com/docs/cloud/channels/zapier/) 

**`{{ JSON.stringify({ myVariable1: workflow.myVariable1, myVariable2: workflow.myVariable2 }) }}`**

However when I use this in the trigger data field on the "send to zapier" card it gives me a type error of the following:

"TypeError: Cannot read properties of undefined (reading 'stringify')"

**Comment by franklevasseur** [comment]
Hi,

The best place to ask question and report issues about Botpress Cloud is the official Botpress [discord server](https://discord.gg/botpress).

I'll close the issue, please feel free to write us on Discord for any future problems.

Cheers,

Frank
