### ISSUE TITLE
Feedback for “CLI”

### ISSUE THREAD

**Issue by YashMengji** [botpress/documentation#228]
The documentation is made with very little description. **It doesn't provide instructions of where files will be located to make changes**. Also the explaination about code is very vague. Please update the documentation thoroughly.

**Comment by franklevasseur** [comment]
Hi,

The best place to ask question and report issues about Botpress Cloud is the official Botpress [discord server](https://discord.gg/botpress).

I'll close the issue, please feel free to write us on Discord for any future problems.

Cheers,

Frank
