### ISSUE TITLE
Feedback for “Web Chat”

### ISSUE THREAD

**Issue by azpat09** [botpress/documentation#57]
I am unable to embed my html script in my WIX website!  WIX says the Botpress code is not compatible with the WIX server- Is there a fix for this?
My preconfigured code is:

<script src="https://cdn.botpress.cloud/webchat/v0/inject.js"></script>
<script src="https://mediafiles.botpress.cloud/099d625c-f020-4564-97e4-1f42359bf6>

WIX syas this is NOT their problem.

I am beyond stressed!

Please help me fix this ASAP!

Patrick OConnell
innovativedigitalmarketing@protectmykid.us

**Comment by lakshya0246** [comment]
@azpat09 can you try asking for help in the botpress discord community [https://discord.com/invite/botpress]
